
              UNAME  := $(shell uname -s)

ifeq "$(UNAME)" "CYGWIN_NT-6.1-WOW64"
         EXTERN_ROOT := $(PROJECT_ROOT)/../extern/i686-pc-mingw32
               SHLIB := dll
endif

$(SHLIB_PRE)mnebase.$(SHLIB).ISDLL := TRUE
$(SHLIB_PRE)mnebase.$(SHLIB).WITH_GD := FALSE
$(SHLIB_PRE)mnebase.$(SHLIB).WITH_POSTGRES := FALSE
$(SHLIB_PRE)mnebase.$(SHLIB).LIBMAJOR := 1
$(SHLIB_PRE)mnebase.$(SHLIB).LIBMINOR := 0
$(SHLIB_PRE)mnebase.$(SHLIB).SOURCES := \
        \
		$(PROJECT_ROOT)/allg/argument/argument.cpp \
		$(PROJECT_ROOT)/allg/utils/cslist.cpp \
		$(PROJECT_ROOT)/allg/utils/gettimeofday.c \
		$(PROJECT_ROOT)/allg/utils/check_mem.cpp \
        $(PROJECT_ROOT)/allg/utils/process.cpp \
        $(PROJECT_ROOT)/allg/message/message.cpp \
        $(PROJECT_ROOT)/allg/ipc/s_socket.cpp \
        $(PROJECT_ROOT)/allg/deamon/deamon.cpp \
        $(PROJECT_ROOT)/allg/crypt/base64.cpp \
        $(PROJECT_ROOT)/allg/network/wake.cpp \
        $(PROJECT_ROOT)/allg/bonjour/dnsserviceregister.cpp \

$(SHLIB_PRE)mnecrypt.$(SHLIB).ISDLL := TRUE
$(SHLIB_PRE)mnecrypt.$(SHLIB).WITH_GD := FALSE
$(SHLIB_PRE)mnecrypt.$(SHLIB).WITH_POSTGRES := FALSE
$(SHLIB_PRE)mnecrypt.$(SHLIB).LIBMAJOR := 1
$(SHLIB_PRE)mnecrypt.$(SHLIB).LIBMINOR := 0
$(SHLIB_PRE)mnecrypt.$(SHLIB).LIBS := mnebase
$(SHLIB_PRE)mnecrypt.$(SHLIB).SOURCES := \
        \
        $(PROJECT_ROOT)/allg/crypt/hashes.cpp \
        $(PROJECT_ROOT)/allg/crypt/cipher.cpp \

$(SHLIB_PRE)mnemail.$(SHLIB).ISDLL := TRUE
$(SHLIB_PRE)mnemail.$(SHLIB).WITH_GD := FALSE
$(SHLIB_PRE)mnemail.$(SHLIB).WITH_POSTGRES := FALSE
$(SHLIB_PRE)mnemail.$(SHLIB).LIBMAJOR := 1
$(SHLIB_PRE)mnemail.$(SHLIB).LIBMINOR := 0
$(SHLIB_PRE)mnemail.$(SHLIB).SOURCES := \
        $(PROJECT_ROOT)/allg/mail/imap.cpp \
        $(PROJECT_ROOT)/allg/mail/imap_scan.cpp

$(SHLIB_PRE)mnehttp.$(SHLIB).ISDLL := TRUE
$(SHLIB_PRE)mnehttp.$(SHLIB).WITH_GD := FALSE
$(SHLIB_PRE)mnehttp.$(SHLIB).WITH_POSTGRES := FALSE
$(SHLIB_PRE)mnehttp.$(SHLIB).LIBMAJOR := 1
$(SHLIB_PRE)mnehttp.$(SHLIB).LIBMINOR := 0
$(SHLIB_PRE)mnehttp.$(SHLIB).LIBS := mnebase
$(SHLIB_PRE)mnehttp.$(SHLIB).SOURCES := \
                $(PROJECT_ROOT)/allg/embedweb/http_analyse.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_translate.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_cookie.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_vars.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_map.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_utils.cpp \
                $(PROJECT_ROOT)/allg/embedweb/http_search.cpp \

$(SHLIB_PRE)mnesqlite.$(SHLIB).ISDLL := TRUE
$(SHLIB_PRE)mnesqlite.$(SHLIB).WITH_GD := FALSE
$(SHLIB_PRE)mnesqlite.$(SHLIB).WITH_POSTGRES := FALSE
$(SHLIB_PRE)mnesqlite.$(SHLIB).LIBMAJOR := 1
$(SHLIB_PRE)mnesqlite.$(SHLIB).LIBMINOR := 0
$(SHLIB_PRE)mnesqlite.$(SHLIB).SOURCES := \
        \
        $(PROJECT_ROOT)/allg/sqlite/sqlite3.c \

wake.WITH_GD := FALSE
wake.WITH_POSTGRES := FALSE
wake.LIBS    := mnebase
wake.SOURCES := $(PROJECT_ROOT)/allg/network/wake_main.cpp 
                